### ISSUE TITLE
Run Does Not Work

### ISSUE THREAD

**Issue by joonho3020** [mabdullahsoyturk/boot-tests#1]
Command I Used : 
gem5/build/X86/gem5.opt gem5/configs/fs_config/run.py --image=disk-image/boot-and-exit-image/boot-and-exit --kernel=linux/vmlinux 

Environment : Docker Image Ubuntu 20.04 with all dependencies installed

Error Message : 
- gem5/configs/fs_config/system/system.py
- class MySystem(LinuxX86System):
- NameError : LinuxX86System is not defined

Steps 1 through 4 was successful.
However I get this error when trying to run your config code.
Can you please help me out??

**Comment by mabdullahsoyturk** [comment]
gem5's Python api for LinuxX86System has been updated with Version 20.0.0.0. If you checkout your gem5 version to 19.0.0.0, it should work.

Here is the related release note: [Release Note](https://github.com/gem5/gem5/blob/cd21b5a5519940a0fa9b9a2dde68f30403d17f7e/RELEASE-NOTES.md)

Edit: I updated the Medium post.

**Comment by joonho3020** [comment]
Oh now it works.
One note is that now I had to use python2 instead of python3 to build gem5.
Anyways, thanks a lot.
Your post was very helpful!

**Comment by Abhijeeth28** [comment]
> gem5's Python api for LinuxX86System has been updated with Version 20.0.0.0. If you checkout your gem5 version to 19.0.0.0, it should work.
> 
> Here is the related release note: [Release Note](https://github.com/gem5/gem5/blob/cd21b5a5519940a0fa9b9a2dde68f30403d17f7e/RELEASE-NOTES.md)
> 
> Edit: I updated the Medium post.

Can you help me how to change version of gem5 please?

**Comment by mabdullahsoyturk** [comment]
@Abhijeeth28 You can checkout to 19.0.0 with the following command: git checkout tags/v19.0.0.0
